---
# AWS Windows-specific overrides
# These override both platform and provider defaults

# Windows Server 2025 in eu-north-1
#
# Prerequisite for searching an AMI
#
# - log into Amazon EC2 Console https://console.aws.amazon.com/ec2/
# - select your region in the top right corner (e.g., "Europe (Stockholm) eu-north-1")
#
# To locate a newer version of the AMI used below,
#
# - in the AMI Catalog, activate the "Community-AMIs" tab
# - enter "Windows_Server-2025-English-Full-Base" into the search box
# - in the results, search for an AMI starting with exactly the same name
#   and ending with a date like 2025.08.13
#
#
aws_default_ami_id: "ami-02d780a7b1609ebca"

# Refer to the pricing table in inventories/group_vars/aws_ec2_linux/vars.yml
aws_default_instance_type: "t3.large"
