---
- name: Restore Chromium settings
  hosts: linux
  tags: not-supported-on-vagrant-docker
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"

  tasks:

    - name: Restore Chromium settings
      include_tasks: restore.yml
      vars:
        users: "{{ desktop_users | map(attribute='name') | list }}"
        backup_file: "chromium-backup.tar.gz"
        destination_beneath_home: "snap/chromium/common/chromium/Default"
        delete_before_beneath_home:
          - "snap/chromium/common/chromium/Default"
