---
- name: Restore home folder files
  hosts: linux
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"

  tasks:

    - name: Restore home folder files
      include_tasks: restore.yml
      vars:
        users: "{{ desktop_users | map(attribute='name') | list }}"
        source_path: "{{ playbook_dir }}/../../configuration/home/my_desktop_user/backup/home-folder-files-backup.tar.gz"
        destination_beneath_home: ""
