---
- name: Restore home folder files
  hosts: linux
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"

  tasks:

    - name: Restore home folder files
      include_tasks: restore.yml
      vars:
        users: "{{ desktop_users | map(attribute='name') | list }}"
        backup_file: "home-folder-files-backup.tar.gz"
        destination_beneath_home: ""
