---
- name: Backup Cursor settings
  hosts: linux
  tags: not-supported-on-vagrant-docker
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"
    backup_user: "{{ desktop_users[0].name }}"
    extensions_remote_file: "/home/{{ backup_user }}/cursor-extension-list.txt"

  tasks:

    - name: Export list of extensions
      shell: cursor --list-extensions > "{{ extensions_remote_file }}"
      become_user: "{{ backup_user }}"

    - import_tasks: backup.yml
      vars:
        path:
          - "{{ extensions_remote_file }}"
          - "/home/{{ backup_user }}/.cursor"
          - "/home/{{ backup_user }}/.config/Cursor/User"
        temp_backup_path: "/home/{{ backup_user }}/cursor-backup.tar.gz"
        dest: "{{ playbook_dir }}/../../configuration/home/my_desktop_user/backup/cursor-backup.tar.gz"
        exclusion_patterns:
          - "*extensions*"

    - name: Delete list of extensions from remote
      file:
        path: "{{ extensions_remote_file }}"
        state: absent
