---
- name: Backup files in home directory
  hosts: linux
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"
    backup_user: "{{ desktop_users[0].name }}"

  tasks:
    - include_tasks: backup.yml
      vars:
        path:
          - "/home/{{ backup_user }}/.gitconfig"
        backup_file: "home-folder-files-backup.tar.gz"
