---
- name: Backup keyring
  hosts: linux
  tags: not-supported-on-vagrant-docker
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"
    backup_user: "{{ desktop_users[0].name }}"

  tasks:
    - include_tasks: backup.yml
      vars:
        path: "/home/{{ backup_user }}/.local/share/keyrings"
        temp_backup_path: "/home/{{ backup_user }}/keyrings-backup.tar.gz"
        backup_file: "keyrings-backup.tar.gz"
