---
- name: Backup Visual Studio Code settings
  hosts: linux
  tags: not-supported-on-vagrant-docker
  become: true

  vars:
    ansible_user: "{{ my_ansible_user }}"
    backup_user: "{{ desktop_users[0].name }}"
    extensions_remote_file: "/home/{{ backup_user }}/vscode-extension-list.txt"

  tasks:

    - name: Export list of extensions
      shell: code --list-extensions > "{{ extensions_remote_file }}"
      become_user: "{{ backup_user }}"

    - include_tasks: backup.yml
      vars:
        path:
          - "{{ extensions_remote_file }}"
          - "/home/{{ backup_user }}/.vscode"
          - "/home/{{ backup_user }}/.config/Code/User"
        backup_file: "vscode-backup.tar.gz"
        exclusion_patterns:
          - "*extensions*"

    - name: Delete list of extensions from remote
      file:
        path: "{{ extensions_remote_file }}"
        state: absent
